# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zero < Formula
  desc "Allow startup developers to ship to production on day 1."
  homepage "https://github.com/commitdev/zero"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/commitdev/zero/releases/download/v0.2.6/zero_0.2.6_Darwin_arm64.tar.gz"
      sha256 "7e78424060c8cf4e8d9bc2d1f78b28c4f56d42714175a5e81e2838281d68a329"

      def install
        bin.install "zero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/commitdev/zero/releases/download/v0.2.6/zero_0.2.6_Darwin_x86_64.tar.gz"
      sha256 "7b686599f1f0aefd2449c01e643ac5cdb493271b4ccc30b03f1f6b1868443a01"

      def install
        bin.install "zero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/commitdev/zero/releases/download/v0.2.6/zero_0.2.6_Linux_arm64.tar.gz"
      sha256 "ec51c881c064e9f0ca2e17d9649198c9aaf91df5e67e116e53cbfb64bfacceb0"

      def install
        bin.install "zero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/commitdev/zero/releases/download/v0.2.6/zero_0.2.6_Linux_x86_64.tar.gz"
      sha256 "c31a2c8491ba6121bcd13543d792a5f4c0bad7f62b3e91d0f9e203683f0192db"

      def install
        bin.install "zero"
      end
    end
  end

  depends_on "git" => :optional
  depends_on "terraform" => :optional
  depends_on "jq" => :optional
  depends_on "awscli" => :optional
  depends_on "kubectl" => :optional
  depends_on "wget" => :optional

  test do
    system "#{bin}/zero version"
  end
end
